include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
    - test/**
    - packages/nonstop_cli/bricks/**
linter:
  rules:
    constant_identifier_names: false
    directives_ordering: true
