name: flutter_forge_workspace

packages:
  - plugins/*
  - plugins/*/*
  - packages/*
  - packages/*/*

command:
  version:
    workspaceChangelog: false
    fetchTags: true
    updateGitTagRefs: false
    
    linkToCommits: false
    hooks:
      post: melos run update_nonstop_cli_version

scripts:
  lint: dart format . --set-exit-if-changed && flutter analyze --fatal-infos .
  update_nonstop_cli_version:
    run: dart run tools/update_nonstop_cli_version.dart
  bundle-project:
    run: |
      dart pub global activate mason_cli
      mason bundle packages/nonstop_cli/bricks/nonstop_project -t dart -o packages/nonstop_cli/lib/commands/create
      dart format packages/nonstop_cli/lib/commands/create/nonstop_project_bundle.dart