name: flutter_forge_workspace

packages:
  - plugins/*
  - plugins/*/*
  - packages/*
  - packages/*/*
  - packages/nonstop_cli/bricks/flutter_app_for_mono_repo/hooks
  - packages/nonstop_cli/bricks/flutter_package_for_mono_repo/hooks
  - packages/nonstop_cli/bricks/flutter_project_with_mono_repo/hooks

command:
  version:
    workspaceChangelog: false
    fetchTags: true
    updateGitTagRefs: false
    
    linkToCommits: false
    hooks:
      post: melos run update_nonstop_cli_version
      pre: melos run update_nonstop_cli_bundles

scripts:
  lint: dart format . --set-exit-if-changed && flutter analyze --fatal-infos .
  update_nonstop_cli_version:
    run: dart run tools/update_nonstop_cli_version.dart
  update_nonstop_cli_bundles:
    run: dart run tools/update_nonstop_cli_bundles.dart

