name: flutter_forge_workspace
description: A place where Flutter packages are crafted and built.

packages:
  - plugins/*
  - plugins/*/*
  - packages/*
  - packages/*/*

command:
  version:
    workspaceChangelog: false

scripts:
  lint: dart format . --set-exit-if-changed && flutter analyze --fatal-infos .