name: flutter_forge
description: A place where Flutter packages are crafted and built.

environment:
  sdk: '>=3.2.0 <4.0.0'

dev_dependencies:
  flutter_lints: ^5.0.0
  melos: ^6.2.0

flutter:
  uses-material-design: true
