name: cli_utils
description: Shared utilities for CLI operations in Flutter Forge packages.
version: 0.0.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mason: ^0.1.0-dev.59
  mason_logger: ^0.3.1
  path: ^1.8.0

dev_dependencies:
  test: ^1.24.9